### ISSUE TITLE
When to use --remove-orphans flag

### ISSUE THREAD

**Issue by buzzfrog** [Azure/iotedgehubdev#101]
When I run the follow command:
```
PS C:\Users\dagk> iotedgehubdev stop
WARNING: Found orphan containers (tempSensor, SampleModule, edgeHubDev) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
IoT Edge Simulator has been stopped successfully.
PS C:\Users\dagk> iotedgehubdev stop --remove-orphans
Error: no such option: --remove-orphans
```
It is unclear when I really can use the flag --remove-orphans

**Comment by LazarusX** [comment]
This message is the output of docker-compose command which the `iotedgehubdev stop` command calls internally. Currently, we won't pass the `--remove-orphans` flag yet to docker-compose. You can manually do it with `docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml down --remove-orphans`. On the other hand, this is just a warning (see https://github.com/docker/compose/issues/3490#issuecomment-221091913).

**Comment by LazarusX** [comment]
Close due to inactivity. Please reopen if the solution above does not work.
