### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by chris-to-pher** [Azure/iotedgehubdev#125]
After running `iotedgehubdev start -d "c:\...\config\deployment.json" -v`, I am seeing this error:

`ERROR: Error: Error while checking status for: cert_helper : 500 Server Error: Internal Server Error ("readlink /var/lib/docker/overlay2/l: invalid argument")`

**Comment by adashen** [comment]
@chris-to-pher , seems docker issue. ref https://github.com/docker/for-mac/issues/1396

**Comment by chris-to-pher** [comment]
Thanks for your feedback. This error is thrown on a Windows machine.

**Comment by LazarusX** [comment]
Looks like an issue with Docker. Closing.
