### ISSUE TITLE
Is really hello-world:latest the best image to pull?

### ISSUE THREAD

**Issue by buzzfrog** [Azure/iotedgehubdev#126]
I see that you pull this image as a helper image from docker hub each time you do Build and Run in Simulator. 
Isn't it better to pull a image that we have control over?
/dag

**Comment by adashen** [comment]
@buzzfrog , Thanks for the comments. hello-world:latest is from docker official. And it is a very small image which we used to do some preparing stuff.
I will close the issue, since it is not an user experience issue. If you think this blocks your experience. Feel free to re open it.
