### ISSUE TITLE
not support Stream Analytics Module

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#133]
1.  create new solution for Stream Analytics Module, 
```
please make sure there is at least one Stream Analytics Jobs in your subscription (You can refer this tutorial to create ASA for Edge), 
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics
2.click the deployment.template.json and generate deployment
3.click the deployment.json and run iot edge in simulator.
4.veirfy the docker logs of Stream Analytics Module, 
iot@iot-box:~$ docker logs SampleModule
2018-11-20 22:08:40.094 +00:00 [INF] - Module client initializing ... 
2018-11-20 22:08:44.506 +00:00 [INF] - Opened module client connection
2018-11-20 22:08:45.986 +00:00 [INF] - ASA getting path: https://czgstorage.blob.core.windows.net/czgcontainer/ASAEdgeJobs/7dfb3299-b414-47b7-bb1d-636b79ae9a15/e07db6d0-8586-47a9-a62d-f7970cabd253/ASAEdgeJobDefinition.zip?sv=2017-04-17&sr=b&sig=Kupbj20TO8c%2FkBAF%2FVWS%2Bc6gnvwLZp1ox0TRT18JrD8%3D&st=2018-11-20T21%3A43%3A32Z&se=2021-11-20T21%3A53%3A32Z&sp=r
2018-11-20 22:08:47.804 +00:00 [INF] - Unzip ASA job definition ...
2018-11-20 22:08:47.821 +00:00 [INF] - Initalizing ASA Engine ...
2018-11-20 22:08:48.576 +00:00 [INF] - 
==================================Metrics report==================================
 Errors                                       :                   0
 DroppedInputEventsBeforeApplicationStartTime :                   0
 EarlyInputEvents                             :                   0
 LateInputEvents                              :                   0
 DeserializationError                         :                   0
 InputEventBytes                              :                 0 B
 DroppedOrAdjustedEvents                      :                   0
 InputEvents                                  :                   0
 OutputEvents                                 :                   0
==================================================================================

2018-11-20 22:08:52.724 +00:00 [INF] - ASA module registered message endpoint : [temperature]
2018-11-20 22:09:40.653 +00:00 [INF] - Module reported job status successfully, Job Status : Idle, Is Runtime Error : False
2018-11-20 22:09:48.580 +00:00 [INF] - 
==================================Metrics report==================================
 Errors                                       :                   0
 DroppedInputEventsBeforeApplicationStartTime :                   0
 EarlyInputEvents                             :                   0
 LateInputEvents                              :                   0
 DeserializationError                         :                   0
 InputEventBytes                              :                 0 B
 DroppedOrAdjustedEvents                      :                   0
 InputEvents                                  :                   0
 OutputEvents                                 :                   0
==================================================================================
```

**Comment by adashen** [comment]
@czgtest we need device twin setup for ASA module right? Please send the device twin content to the module through toolkit and try again?

**Comment by hubez** [comment]
@adashen, @czgtest I am interested in device twin sending when using iotedgehubdev. Is there info on how I can trigger this? I too am looking for ASA support on iotedgehubdev.

**Comment by hubez** [comment]
> @adashen, @czgtest I am interested in device twin sending when using iotedgehubdev. Is there info on how I can trigger this? I too am looking for ASA support on iotedgehubdev.

Nevermind, found my answer: https://github.com/Azure/iotedgehubdev/issues/152#issuecomment-453891392

**Comment by hubez** [comment]
I've published via the VS Code IOT Hub Toolkit an appropriate device twin such that it triggers proper grabbing of the ASA job, but then it shuts down complaining:

 2019-02-28 04:57:04.116 +00:00 [INF] - Job billing id is invalid or is missing from container environment variable, shutting down...

Any workarounds?

**Comment by adashen** [comment]
@hubez it seems related to the "The plan id is needed for billing purposes and without the plan id the Stream Analytics container does not operate correctly." Please refer to https://www.danielstechblog.io/stream-analytics-on-iot-edge-deployment-changes/ . You may need to add the "PlanId=REDACTED" in the create option for container environment

**Comment by hubez** [comment]
@adashen Thanks, that link gave me my answer! ASA running successfully on iotedgehubdev now! Now I just wish there was a less brutal way to update it with updates to the ASA job during my dev-test loop.

**Comment by adashen** [comment]
@hubez Thanks for the feedback. We would populate the PlanID env in VSCode Edge extension to avoid this manual step.

**Comment by czgtest** [comment]
now iotedgehubdev support ASA module, 
steps:
1.	create new solution for ASA , select ASA job
2.click the deployment.template.json and generate deployment
3.edit module twin for device
![image](https://user-images.githubusercontent.com/35018765/55222677-7b854d00-5247-11e9-9109-5a8d51b03353.png)

4.click the deployment.json and run IoT edge in simulator.
![image](https://user-images.githubusercontent.com/35018765/55222656-6f998b00-5247-11e9-8250-1c9d6079da11.png)
