### ISSUE TITLE
Start an IoT Edge solution in simulator failed when edge device named "edgeDeviceC#"

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#142]
1. create an edge device  :  edgeDeviceC#
2. setup IoT edge simulator
3. run IoT edge solution in simulator

get error:
```
PS D:\test\test\1205\EdgeSolution13> iotedgehubdev start -d "d:\test\test\1205\EdgeSolution13\config\deployment.amd64.json" -v
ERROR: Error:
```

Device connection string: `HostName=anotheriothub.azure-devices.net;DeviceId=edgeDeviceC#;SharedAccessKey=<redacted by Ray>`

**Comment by adashen** [comment]
@czgtest  Please try to use the device connection string for edge runtime. And deploy to that device, to check whether the id could work for edge runtime.

**Comment by czgtest** [comment]
edge runtime service cannot be start after user device connection string of "edgeDeviceC#"

**Comment by czgtest** [comment]
close it as by design
