### ISSUE TITLE
"on-unhealthy" restart policy is not supported

### ISSUE THREAD

**Issue by adashen** [Azure/iotedgehubdev#148]
Sample deployment.template.json:
https://github.com/Azure/iotedge/blob/master/stress/deployment.template.json

"on-unhealthy" restart policy for influxdb will be treated as un-supported

**Comment by LazarusX** [comment]
@adashen Looks like the link above is 404 now.

**Comment by LazarusX** [comment]
"on-healthy" restart policy is not yet supported by docker-compose (https://docs.docker.com/compose/compose-file/#restart_policy) and Docker engine (https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate)

**Comment by LazarusX** [comment]
Partial support which falls back to "always" is added in https://github.com/Azure/iotedgehubdev/pull/154.

**Comment by SLdragon** [comment]
Close due to already added fall back mechanism
