### ISSUE TITLE
ModuleClient.GetTwinAsync doesn't return the device twin from the ioT hub

### ISSUE THREAD

**Issue by fabinshen** [Azure/iotedgehubdev#152]
It seems that: although we set device twin properties in azure portal, the properties was not returned by moduleClient.GetTwinAsync when running under iotedgehubdev simulator.

We want to store some configuration data in twin.desired properties. However, if we cannot get the real twin properties from the ioT hub under the iotedgehubdev simulator (where we debug our module), then it is not straightforward to debug the code due to the missing configurations.

**Comment by LazarusX** [comment]
Hi @fabinshen, thanks for reporting this issue.

`ModuleClient` only supports twin properties at module level. For your requirement, you can set your configuration data in the module twin.

In VS Code, you can:
1. Click your device in the left bottom corner to expand the module list
1. Right click on the module which will consume the properties
1. Select "Edit Module Twin"
1. Edit the module twin in the opened editor tab, and click the "Update Module Twin" on top of the editor or in the right-click context menu:
![image](https://user-images.githubusercontent.com/716650/51094683-0f6b7f00-17ea-11e9-91cf-25e90cb03d7e.png)

Editing module twin is also supported on Azure Portal.

**Comment by fabinshen** [comment]
Thank you LazarusX! that resolves the issue.
