### ISSUE TITLE
Start in single module mode failed with a fresh machine

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgehubdev#156]
```
> iotedgehubdev start -i "input1,input2"
ERROR: Error: Error while executing command: docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml down. [WinError 2] The system cannot find the file specified
```

**Comment by furlongmt** [comment]
Hi,

I'm currently having the same problem when trying to deploy a single module. What did you do to solve this issue?

**Comment by adashen** [comment]
@furlongmt Thanks for reporting the issue. We tried to reproduce the issue on a fresh machine but failed to reproduce it. And can you check whether you are using the latest version 0.8.0. And if the issue still exists, Please help to provide the error log.

**Comment by furlongmt** [comment]
Yes, I'm using version 0.8.0 on Ubuntu 16.04. 

I setup the edge simulator using VS Code (version 1.34.0) and then run:
 `iotedgehubdev start -i "input1"`
 which fails with the following error:

**ERROR: Error while executing command: docker-compose -f /var/lib/iotedgehubdev/data/docker-compose.yml down. [Errno 2] No such file or directory: 'docker-compose'**

My VM has Docker version 18.09.6 and docker-compose version 1.24.0. 

Please let me know if I can provide anymore information to assist.

**Comment by adashen** [comment]
@furlongmt , can you try "sudo iotedgehubdev start -i "input""?
