### ISSUE TITLE
VSCode on Mac does not detect iotedgehubdev version 0.6.0

### ISSUE THREAD

**Issue by nelsonmorais** [Azure/iotedgehubdev#160]
I've installed iotedgehubdev version 0.6.0 on a mac using **sudo pip install --upgrade iotedgehubdev** but VSCode still doesn't detect that **iotedgehubdev** is installed and keeps saying to install it.

**Comment by LazarusX** [comment]
Hi @nelsonmorais, thanks for reporting this issue!

Could you share output of `which iotedgehubdev` and `which python`?

**Comment by nelsonmorais** [comment]
Sure! Here it is:

```
> $ which iotedgehubdev
/usr/local/bin/iotedgehubdev

> $ which python
/usr/bin/python
```

**Comment by LazarusX** [comment]
Thanks @nelsonmorais.

What's the output of `iotedgehubdev --version` then? And is your Python shipped with macOS or installed via Homebrew?

**Comment by nelsonmorais** [comment]
Hi @LazarusX,

Here's the info:

```
> $ iotedgehubdev --version
iotedgehubdev, version 0.6.0

> $ brew list
...
python 3.7.0 3.7.1 3.6.4_2
...

> $ python --version
Python 2.7.10
```

Note that ```python --version``` reports 2.7.10 but from Homebrew I have installed 3.x.
As far as I remember I did not install Python 2.7.10 so I'm assuming it was shipped with macOS.

**Comment by LazarusX** [comment]
Did you run these commands in VS Code terminal? If not, could you help paste results from VS Code terminal?

**Comment by nelsonmorais** [comment]
Yes, these were executed in the VSCode terminal. 
As an extra info, in the VSCode terminal I can manually execute the iotedgehubdev CLI commands, but it would be better to just use them via VSCode and have the warning saying that iotedgehubdev is missing go away.

**Comment by LazarusX** [comment]
Thanks. I asked just to make sure that the environment where our code checks whether iotedgehubdev is installed is the same as the one where you get the version information. I am still investigating this issue.

**Comment by nelsonmorais** [comment]
Hi @LazarusX, same issue after installing the new version.

**Comment by LazarusX** [comment]
Thanks for the update. We'll keep investigating.

**Comment by LazarusX** [comment]
Hi @nelsonmorais, thanks for your patience.

Could you share output of `which iotedgehubdev` and `which python` in terminal *outside* VS Code?

In addition, do you have VS Code Python extension installed?

As a workaround, you should be able to use the iotedgehubdev integration in VS Code by downgrading the VS Code Edge extension to 1.7.0:
![image](https://user-images.githubusercontent.com/716650/52763608-6a95c900-3057-11e9-87e5-f5f9e41478b4.png)

**Comment by nelsonmorais** [comment]
Hi @LazarusX 

Here's the info (this was already shared previously - see thread above):

```
> $ which iotedgehubdev
/usr/local/bin/iotedgehubdev

> $ which python
/usr/bin/python
```

I do have VS Code Python extension installed. Version is: 2019.2.5433

**Comment by LazarusX** [comment]
Can you try if you can still reproduce this issue by quitting and relaunching VS Code via terminal with `code path/to/project/directory`?

**Comment by nelsonmorais** [comment]
It seems to be working now!
Don't know exactly what has changed, but VSCode is now able to detect that iotedgehubdev is installed.

**Comment by LazarusX** [comment]
Thanks @nelsonmorais for the update! Glad to know that the workaround worked for you. I just filed an issue for VS Code: https://github.com/Microsoft/vscode/issues/69728.
