### ISSUE TITLE
“azure iot edge”  words display incorrect in vscode when start -d deployment

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#164]
![image](https://user-images.githubusercontent.com/35018765/51575943-39f6bf80-1eef-11e9-81d6-c8c18e27310a.png)

expected:
![image](https://user-images.githubusercontent.com/35018765/51575961-48dd7200-1eef-11e9-8d58-c6b582ad0a70.png)

**Comment by LazarusX** [comment]
A reboot fixed this issue.
