### ISSUE TITLE
support allow modules to be started on the hostnetwork

### ISSUE THREAD

**Issue by adashen** [Azure/iotedgehubdev#183]
module create options = "{\"NetworkingConfig\":{\"EndpointsConfig\":{\"host\":{}}},\"HostConfig\":{\"NetworkMode\":\"host\"}}"

Currently the above createOption will cause a wrong docker compose file with both host mode and azure-iot-edge-dev netowrk configured. We need add azure-iot-edge-dev network only user doesn't config network.
Ref https://github.com/Azure/iotedge/commit/e2006e0a4b098cf63913b6ff511a85b2cdc86bb7

**Comment by SLdragon** [comment]
Fixed
