### ISSUE TITLE
ARM Platform Support for iotedgehubdev

### ISSUE THREAD

**Issue by toolboc** [Azure/iotedgehubdev#184]
I am working with a customer who is running an IoT Edge deployment on an Nvidia Jetson TX2 device running `Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu May 17 00:15:19 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux`

As development has progressed, it made sense to investigate the potential for running the inner-dev loop (VSCode, iotedgehubdev) on the Nvidia Jetson TX2  to reduce development/test friction incurred by platform incompatibilities when using a foreign host for development.

We were able to successfully install an aarch64 build of VS Code from https://code.headmelted.com/ and install all necessary extensions (Azure Account, Azure IoT Edge, Azure IoT Hub Toolkit).  

We then created a new Edge Solution and Edge Module (C) and attempted to run the "Build and Run IoT Edge in Simulator" task.  We noticed a few interesting things:

1.) The iotedgehubdev tool always assumes that we want to build for AMD64.  However, we can override the module.json to point all platforms to the arm32v7 Dockerfile.  This should probably be something that the user can choose, but were able to make iotedgehubdev build what wanted for our use case with this modification.

2.) The source code for iotedgehubdev dynamically produces a docker-compose file at `/var/lib/iotedgehubdev/data/docker-compose.yml` using the following presupplied image tag: [mcr.microsoft.com/azureiotedge-hub:1.0](https://github.com/Azure/iotedgehubdev/blob/3dc0c935ebf454268d06db9e8d309bf3c14272b5/iotedgehubdev/edgemanager.py#L22).  Unfortunately, the repo that this image is published to does not enforce an architecture specific manifest for aarch64.  As a result, attempting to pull down the image for mcr.microsoft.com/azureiotedge-hub:1.0 on an aarch64 fails as there is no matching manifest entry for aarch64.  This can be worked around by modifying the source to instead reference `mcr.microsoft.com/azureiotedge-hub:1.0.0-linux-arm32v7`.

Hopefully we can look into adding support for using iotedgehubdev on ARM platforms as it is an extremely common target for IoT Solutions.  We feel this scenario is likely to pick up in adoption due to the [recent announcement of Nvidia and Microsoft's partnership to enable IoT Edge scenario on GPU accelerated hardware](https://twitter.com/samjgeorge/status/1108000507614777344).

**Comment by adashen** [comment]
@toolboc Thanks for the feedback. As for the issues
for 1)  Can you check the platform setting in VSCode?  You could find it at the status bar of vscode. And by clicking it, it could switch to different platforms, like arm32v7
![image](https://user-images.githubusercontent.com/1872137/55203738-73a5b880-5207-11e9-8af5-4b84ca95fee1.png)

for 2) If you enforce arm32v7 image, you could edit deployment.template.json, and specify the image for $edgeHub.

Please let us know, whether it solves your issues. Thanks

**Comment by adashen** [comment]
Close the issue since the solution is provided and there is no further feedback from user after 10 days.

**Comment by toolboc** [comment]
I was finally able to get my hands on a device for personal testings.  It looks like we may need to repoen this issue.  

When arm32v7 is enforced I  receive the following error message:
```
ERROR: Error while executing command: docker-compose -f /var/lib/iotedgehubdev/data/docker-compose.yml down. [Errno 8] Exec format error
```
![image](https://user-images.githubusercontent.com/2018336/59389922-56c45000-8d35-11e9-8203-81e92011460d.png)

This is due to the explanation provided above:

> The source code for iotedgehubdev dynamically produces a docker-compose file at /var/lib/iotedgehubdev/data/docker-compose.yml using the following presupplied image tag: mcr.microsoft.com/azureiotedge-hub:1.0. Unfortunately, the repo that this image is published to does not enforce an architecture specific manifest for aarch64. As a result, attempting to pull down the image for mcr.microsoft.com/azureiotedge-hub:1.0 on an aarch64 fails as there is no matching manifest entry for aarch64. This can be worked around by modifying the source to instead reference mcr.microsoft.com/azureiotedge-hub:1.0.0-linux-arm32v7.

The can be worked around by modifying the value of ` EDGEHUB_IMG` in https://github.com/Azure/iotedgehubdev/blob/master/iotedgehubdev/edgemanager.py to: mcr.microsoft.com/azureiotedge-hub:1.0.0-linux-arm32v7

I'm curious if this is something that would be best resolved by updating the manifest for the published images provided by iotedge, specifically `mcr.microsoft.com/azureiotedge-hub1.  Perhaps @myagley can provide some insight here as iot edge is beginning to publish preview builds for aarch64.

**Comment by SLdragon** [comment]
Hi, @toolboc , which platform do you use to develop and run vscode ?

**Comment by toolboc** [comment]
@SLdragon , I am developing the module on an Nvidia Jetson Nano device with an ARMv8 Processor running an aarch64 build of Ubuntu 18.04

**Comment by SLdragon** [comment]
@toolboc , if you are developing edge modules on ARM machine, you can change the image url in the deployment.*.json file to support ARM:

![image](https://user-images.githubusercontent.com/5545529/59899104-1a27e100-9426-11e9-9530-4033ff817487.png)

Then the docker docker-compose.yml would be update to ARM:
![image](https://user-images.githubusercontent.com/5545529/59899266-b651e800-9426-11e9-92ec-e88beab080a6.png)
