### ISSUE TITLE
Allow setting environment variable when start single module mode

### ISSUE THREAD

**Issue by blackchoey** [Azure/iotedgehubdev#187]
I set DOCKER_HOST to my raspberry pi and started iotedgehubdev in single module mode. When debugging modules the edgeHub container will throw OutOfMemory exception.
In order to resolve this problem, we need to allow setting environment variable when start single module mode, where I can disable OptimizeForPerformance for edgeHub.

**Comment by SLdragon** [comment]
Already added this feature
