### ISSUE TITLE
Define environment variable for edgeHubDev?

### ISSUE THREAD

**Issue by sebader** [Azure/iotedgehubdev#193]
For a test I need edgeHubDev to connect over MQTT instead of AMQP to the IoT Hub. This can usually be done by setting the env variable UpstreamProtocol on the edgeHub. How can this be done in the simulator?

**Comment by SLdragon** [comment]
Hi, @sebader ,
You can add env for edgeHub in deployment manifest, and then "Build and Run IoT Edge Solution in Simulator":

```
"edgeHub": {
"type": "docker",
"settings": {
"image": "mcr.microsoft.com/azureiotedge-hub:1.0",
"createOptions": ""
},
"env": {
"[YOUR ENVS}"
}
},
"status": "running",
"restartPolicy": "always"
}

```

You can find a related disscuss here:  https://github.com/Azure/iotedgehubdev/issues/151

**Comment by sebader** [comment]
Ah sorry, I should have added that I need this for the single module simulator, not the deployment version.

**Comment by SLdragon** [comment]
Hi, @sebader, define envrionment variables when starting in single module is in our plan (https://github.com/Azure/iotedgehubdev/issues/105). For current version, if you want to define envrionment variables for edgeHubDev, you can only use solution mode.

**Comment by SLdragon** [comment]
Already added this feature in new vesrion
