### ISSUE TITLE
Need better error message

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [Azure/iotedgehubdev#206]
Erroneously attempting to debug an Edge configuration on a non-Edge device gives the following uninformative error:
```
$ iotedgehubdev start -d "c:\Clients\AIVideo\AIV-Sample\edge-device\AIVideoEdgeDevice\EdgeDevice\config\deployment.amd64.json" -v
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
ERROR: (400, '{"Message":"ErrorCode:ArgumentInvalid;BadRequest","ExceptionMessage":"Tracking ID:f6d24f224774456a8a75adf4abb3f07e-G:0-TimeStamp:08/11/2019 20:43:15"}')
```
This is such an easy mistake to make, especially for newcomers, that it warrants a helpful error like "Cannot deploy Edge modules to a non-Edge device".

**Comment by SLdragon** [comment]
Thanks for your feedback, maybe we can try to check non-Edge device before start, and would be supported in the future release

**Comment by SLdragon** [comment]
Now with iotedgehubdev 0.12.0 released, it would show more clear error message for non-Edge device, so close this issue, and thanks for your feedback!
