### ISSUE TITLE
how to configure edgehubdev to use amqpws

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedgehubdev#207]
I am trying to get edgehubdev working over a http proxy. But that needs edgehubdev  to use amqp over websockets. How to specify that while starting iotedgehubdev ?

**Comment by adashen** [comment]
@kiranpradeep thanks for the feedback. You could find the setting steps of iotedge runtime in proxy scenario at
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support 

Can you try whether it helps?

**Comment by kiranpradeep** [comment]
@adashen Please see the query is specific to edgehubdev. I had checked the link earlier and it is about setting proxy in iotedge runtime.

**Comment by adashen** [comment]
@kiranpradeep iotedgehubdev does not use edgeAgent, so there is no need to config config.yaml. And you can follow https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#json-deployment-manifest-files to config the "edgeHub" module in JSON deployment manifest.

**Comment by kiranpradeep** [comment]
@adashen Thanks. That helped. After setting _https_proxy_ and _UpstreamProtocol_ (amqpws) env variables, I was able to use edgehubDev over http proxy. 

But, that works only I start in simulator mode with deployment manifest template. When I start edgehubDev for single module debugging, the env variables are not in effect (verified with _docker inspect edgeHubDev_) and so edgeHubDev cannot connect over proxy. How to set the env variables with edgeHubDev so that single module debugging works over http proxy?

**Comment by adashen** [comment]
@kiranpradeep The latest version 0.10.0 has just added the support for env in single module debugging. (https://github.com/Azure/iotedgehubdev/releases/tag/v0.10.0)
You could use "-e" option to add the envs when starting the simulator.
