### ISSUE TITLE
If the device does not belong to the iothub. Error is not shown

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#214]
repro on v0.11.0rc0

Step:
1. Run “iotedgehubdev setup –c <edge device connection string> -i <iothub connection string>” 
expect :  If the device does not belong to the iothub. Error will be shown and fail the setup 
actually:  If the device does not belong to the iothub. Error is not shown and setup successfully

 
![image](https://user-images.githubusercontent.com/35018765/65582485-17520480-dfb0-11e9-9ce6-5e9de1c85bc0.png)

**Comment by adashen** [comment]
@czgtest Actually the host name is same in both device connection string and hub connection string "czghub0925", can  you double check?

**Comment by czgtest** [comment]
OK,  I use the device from another hub , Error will be shown and fail the setup

![image](https://user-images.githubusercontent.com/35018765/65660357-1036ff00-e061-11e9-962b-08bd8da6c863.png)
