### ISSUE TITLE
Can't use powershell to run iotedgehubdev command

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#216]
repro on : Windows10

1. Download standalone binaries from GitHub release page: https://github.com/Azure/iotedgehubdev/releases 
2. Unzip binaries to a folder 
3. Open CMD, navigate to binaries folder, and run iotedgehubdev command
here it work well
4. Open PowerShell , navigate to binaries folder, and run iotedgehubdev command

![image](https://user-images.githubusercontent.com/35018765/65660834-838d4080-e062-11e9-9cfa-5b450c01a3b2.png)

**Comment by czgtest** [comment]
the binaries folder is C:\iotedgehubdev

Open PowerShell , navigate to binaries folder, and run iotedgehubdev command

PS C:\iotedgehubdev> iotedgehubdev.exe --version   failed
PS C:\iotedgehubdev> iotedgehubdev --version   failed
PS C:\iotedgehubdev> .\iotedgehubdev.exe --version  work well
PS D:\> C:\iotedgehubdev\iotedgehubdev.exe --version  work well

**Comment by SLdragon** [comment]
This is by design of powershell
