### ISSUE TITLE
[Windows7]New state of 'nil' is invalid in edgeHubDev logs

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#217]
repro on : Window7

step:
1.install docker on win7 
https://docs.docker.com/toolbox/toolbox_install_windows/ 
2.Download standalone binaries from GitHub release page: https://github.com/Azure/iotedgehubdev/releases
3.Install iotedgehubdev and setup device connection string 
4. iotedgehubdev start -d deployment.json
this deployment.json is form "Test host network" case
5. it has error in edgeHubDev logs
![image](https://user-images.githubusercontent.com/35018765/65738390-336eb680-e114-11e9-905e-9ead21448384.png)

**Comment by adashen** [comment]
https://github.com/moby/moby/issues/22345
