### ISSUE TITLE
[Windows7] Don't support –H option to config DOCKER_HOST

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#220]
Repro on : Windows7

step:
1.Install IoT Edge runtime on a Windows PC. 
the container host is on unsupported build version 7601.

the moby runtime can't install ,so Iotedgehubdev can't use -H option to config docker_host.

![image](https://user-images.githubusercontent.com/35018765/65758418-a9424480-e14b-11e9-8928-ff03ebdf01d2.png)

**Comment by SLdragon** [comment]
Edge runtime is unsupported on win7, so you cannot install it. You can just skip this these test

**Comment by czgtest** [comment]
Got it,  closed it
