### ISSUE TITLE
[ubuntu/mac]docker-compose has not been added as a Python dependency

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#221]
Repro on : ubuntu/mac
sudo pip install git+https://github.com/Azure/iotedgehubdev.git@master

step:
1. Remove the installed docker-compose 
          iotedge@iotedge-Lenovo:/$ which docker-compose
           /usr/local/bin/docker-compose
          iotedge@iotedge-Lenovo:/$ sudo mv /usr/local/bin/docker-compose /usr/local/bin/docker-compose11
2. run iotedgehubdev start –d <deployment manifest> 
Expect :  it could start. Since now docker-compose has been added as a Python dependency 
Acutally:  run failed,  not add docker-compose as Python dependency
iotedge@iotedge-Lenovo:~/Downloads/test/EdgeSolutionCS$ sudo iotedgehubdev start -d "/home/iotedge/Downloads/test/EdgeSolutionCS/config/deployment.debug.amd64.json" -v
[sudo] password for iotedge: 
ERROR: Error while executing command: docker-compose -f /var/lib/iotedgehubdev/data/docker-compose.yml down. [Errno 2] No such file or directory

3. rename the installed docker-compose again

iotedge@iotedge-Lenovo:/$ sudo mv /usr/local/bin/docker-compose11 /usr/local/bin/docker-compose

4. run iotedgehubdev start –d <deployment manifest>  Pass

iotedge@iotedge-Lenovo:~/Downloads/test/EdgeSolutionCS$ sudo iotedgehubdev start -d "/home/iotedge/Downloads/test/EdgeSolutionCS/config/deployment.debug.amd64.json" -v
Network azure-iot-edge-dev is external, skipping
Pulling edgeHubDev ... done
Creating edgeHubDev ... done
Creating SimulatedTemperatureSensor ... done
Creating SampleModule               ... done

**Comment by adashen** [comment]
@czgtest actully after you remove docker-compose, please install iotedgehubdev, to make sure install iotedgehubdev could install docker-compose for user.

**Comment by czgtest** [comment]
step:
1. rename docker-compose
iotedge@iotedge-Lenovo:/$ which docker-compose
/usr/local/bin/docker-compose
iotedge@iotedge-Lenovo:/$ sudo mv /usr/local/bin/docker-compose /usr/local/bin/docker-compose11

2.sudo pip install git+https://github.com/Azure/iotedgehubdev.git@master
3. sudo iotedgehubdev setup -c "HostName=czghub0925.azure-devices.net;DeviceId=edgeubuntu;SharedAccessKey=KTF4xhG3FeqFX/gtypp3u81bw8hEWzwS+PPViiH8nO0="

4. sudo iotedgehubdev start -d deployment.json

iotedge@iotedge-Lenovo:~$ sudo iotedgehubdev start -d Downloads/deployment.json ERROR: Error while executing command: docker-compose -f /var/lib/iotedgehubdev/data/docker-compose.yml down. [Errno 2] No such file or directory

**Comment by czgtest** [comment]
step:
1. sudo mv /usr/local/bin/docker-compose /usr/local/bin/docker-compose22
2. sudo pip uninstall docker-compose
3.sudo pip uninstall iotedgehubdev
4. sudo pip install git+https://github.com/Azure/iotedgehubdev.git@master
5. sudo iotedgehubdev setup -c "HostName=czghub0925.azure-devices.net;DeviceId=edgeubuntu;SharedAccessKey=KTF4xhG3FeqFX/gtypp3u81bw8hEWzwS+PPViiH8nO0="
6. sudo iotedgehubdev start -d Downloads/deployment.json
here it work well

**Comment by czgtest** [comment]
so close it
