### ISSUE TITLE
Could not connect to Docker daemon

### ISSUE THREAD

**Issue by ede0m** [Azure/iotedgehubdev#224]
```
PS C:\> docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:55:51 2019
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\>
```

```
PS C:\> iotedgehubdev.exe start -d C:\dev\PI.ExtrusionData\ExtrusionEdgeData\ExtrusionEdgeData\config\deployment.windows-amd64.json
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
ERROR: Could not connect to Docker daemon. Please make sure Docker is running : Install pypiwin32 package to enable npipe:// support
```

Same result if I select and run "Build and Run IoT Edge Module Simulator".

My docker client app claims it is running. I am pulling images from azure container registry, if that makes a difference. 

Any idea what is going on here?

**Comment by czgtest** [comment]
@ede0m  this issue will repro on Python 3.8.0, pypiwin32 package has conflict,  so Can you try to install Python 3.7.5, then pip install iotedgehubdev again,  it will work well

**Comment by pp012185** [comment]
I have the same situation with the **ERROR: Could not connect to Docker daemon. Please make sure Docker is running : Install pypiwin32 package to enable npipe:// support.**
I set "**DOCKER_HOST=tcp://localhost:2375**" at "**Tools -> Azure IoT Edge Tools -> Iot Edge Tools Setting**".
And it can debug in "single module mode" with iotedgehubdev.
But I still can't debug in "Solution mode"

**Comment by adashen** [comment]
@pp012185 which python version are you using? It seems pypiwin32 package has some issue working on python 3.8.

**Comment by pp012185** [comment]
@adashen  thanks a lot. My python version is 3.8, so I change the version to python 3.7.4. Then, the error above is resolved.

**Comment by SLdragon** [comment]
@pp012185 , thanks for your feedback, and we will investigate whether we can solve the issue for python 3.8, and would let you know the progress!

**Comment by SLdragon** [comment]
https://github.com/docker/docker-py/issues/2454

**Comment by ede0m** [comment]
Switched to 3.7.4 as a workaround, thanks @adashen @SLdragon.

**Comment by SLdragon** [comment]
Now iotedgehubdev version 0.12.0 supported Python 3.8, so close this issue

**Comment by LarsKemmann** [comment]
Just a note that I ran into a seemingly similar issue when trying to create a custom CICD server using a self-hosted DevOps agent:

> `ERROR: ('Could not connect to Docker daemon. Please make sure Docker daemon is running and accessible', DockerException("Error while fetching server API version: (5, 'CreateFile', 'Access is denied.')"))`

The resolution in my case was to run the DevOps agent _interactively_, as the same user that I had installed Docker Desktop for (I was using chocolatey), rather than as a service.
