### ISSUE TITLE
pip install iotedgehubdev v0.12.0-rc0 failed on ubuntu

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#237]
step:
1. login in clean ubuntu without python install
2. sudo apt install python
3. sudo apt install python-pip
4. sudo pip install --index-url https://test.pypi.org/simple/ iotedgehubdev==0.12.0rc0 --extra-index-url https://pypi.org/simple

Install failed :

**Comment by czgtest** [comment]
zun@zun-OptiPlex-790:~$ python --version
Python 2.7.15+
zun@zun-OptiPlex-790:~$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
zun@zun-OptiPlex-790:~$ sudo pip install --index-url https://test.pypi.org/simple/ iotedgehubdev==0.12.0rc0 --extra-index-url https://pypi.org/simple
The directory '/home/zun/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/zun/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting iotedgehubdev==0.12.0rc0
  Downloading https://test-files.pythonhosted.org/packages/e2/b2/17a5c4d4aac42eda241c044b0856a4a8f719ece383787e6a113c02900506/iotedgehubdev-0.12.0rc0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from iotedgehubdev==0.12.0rc0)
Collecting pyOpenSSL>=17.0.0 (from iotedgehubdev==0.12.0rc0)
  Downloading https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 490kB/s 
Collecting requests<2.21,>2.19.1 (from iotedgehubdev==0.12.0rc0)
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 940kB/s 
Collecting docker[ssh]<4.0,>=3.6.0 (from iotedgehubdev==0.12.0rc0)
  Downloading https://files.pythonhosted.org/packages/09/da/7cc7ecdcd01145e9924a8ccbe9c1baf3a362fc75d4cb150676eb5231ea60/docker-3.7.3-py2.py3-none-any.whl (134kB)
    100% |████████████████████████████████| 143kB 1.5MB/s 
Collecting click (from iotedgehubdev==0.12.0rc0)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 6.1MB/s 
Collecting jsonpath-rw (from iotedgehubdev==0.12.0rc0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://test.pypi.org/simple/jsonpath-rw/
zun@zun-OptiPlex-790:~$

**Comment by SLdragon** [comment]
Hi, Chen, seems like pip cannot find the jsonpath-rw library, can you run this command and try again:
```
sudo pip install --index-url https://test.pypi.org/simple/ jsonpath-rw --extra-index-url https://pypi.org/simple
```

**Comment by czgtest** [comment]
this issue will repro again after try above command

**Comment by SLdragon** [comment]
Hi, Chen, please install the package directly through the command below to see whether it works:

```
sudo pip install jsonpath-rw
```

**Comment by czgtest** [comment]
Manually install bellow commands , then iotedgehubdev install pass.

pip install backports.ssl_match_hostname
pip install docker-pycreds
pip install websocket_client
pip install dockerpty
pip install bcrypt
pip install functools32

**Comment by SLdragon** [comment]
Thank you Chen, close this due to test environment issue
