### ISSUE TITLE
[query] need of iotedgehubdev modulecred -l parameter

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedgehubdev#238]
This is not a bug and only a query. I was trying to develop the edge modules in a docker container[[1](https://code.visualstudio.com/docs/remote/containers)] and came to this blocker.

`iotedgehubdev modulecred` has an `-l` parameter which changes GatewayHostName to localhost. Why was this needed? During local debug, if I try connecting with actual hostname(GatewayHostName=real_host_name), the SSL connection fails. Local debug only works with GatewayHostName=localhost. Why is this so? Also `openssl s_client -showcerts -connect 127.0.0.1:8883` shows that the iotedgehubdev server certificate has a fully valid hostname as CN.

**Comment by SLdragon** [comment]
Hi, @kiranpradeep , do you mean that if you try to use the "real_host_name" as GatewayHostName, then it not work?

Could you please share some error messages about it, and here is another issue talk about the GatewayHostName maybe you can refer:
https://github.com/Azure/iotedge/issues/992

**Comment by adashen** [comment]
@kiranpradeep May I know the language you are using? Is it csharp? If so that is the reason we provide localhost, please refer to the issue https://github.com/Azure/azure-iot-sdk-csharp/issues/574

There is a bug when resolving the "fqdn" hostname on the machine. But for "localhost" it could always resolve to the correct ip. That's why we add "localhost" in this scenario.

**Comment by adashen** [comment]
Since it's not an issue, instead of a query and has been answered. Close now. Please feel free to open if there is any other issue.

**Comment by kiranpradeep** [comment]
@adashen @SLdragon I tried now both on an Ubuntu 18.04 LTS and macOS 10.13. In both machines, I could connect(using MQTT protocol) to local edgehubdev using FQDN. Maybe issue [574](https://github.com/Azure/azure-iot-sdk-csharp/issues/574)  got fixed and so `-l` is no more needed. Obviously on macOS we still have issue #30 and so the certificate needs to manually added to key chain. But the `-l` might not be needed anymore.

Of lesser importance: When I raised this issue, I was not aware of this change. I saw this now and wanted to bring it to your attention.

**Comment by SLdragon** [comment]
Hi, @kiranpradeep , thanks for your information, and I checked the SDK code, and also found that they fix this issue 27 days ago.

https://github.com/Azure/azure-iot-sdk-csharp/blob/11e07d7724d8402524211db6846892de284b15de/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L956

**Comment by SLdragon** [comment]
As discussed with team members, we will keep -l parameter due to stability reason, thank you all the same of the information.
