### ISSUE TITLE
the cert path can't be access by edge runtime.

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#242]
repro on v1.12.0-rc0

Test on ubuntu VM:
1.	Create an Azure VM with IoT Edge runtime installed, config DNS name for the Azure VM
2.	Setup IoT Edge runtime, remember to change “hostname” in IoT Edge config to the DNS name
3.	Restart iot edge runtime  here work well
4.	Sudo pip install --index-url https://test.pypi.org/simple/ iotedgehubdev==0.12.0rc0 --extra-index-url https://pypi.org/simple
5.	Sudo iotedgehubdev setup -c “device connection”
6.	sudo nano /etc/iotedge/config.yaml  and  update cert config
certificates:
   device_ca_cert: "/var/lib/iotedgehubdev/certs/edge-chain-ca/cert/edge-chain-ca.cert.pem"
   device_ca_pk: "/var/lib/iotedgehubdev/certs/edge-agent-ca/private/edge-agent-ca.key.pem"
   trusted_ca_certs: "/var/lib/iotedgehubdev/certs/edge-device-ca/cert/edge-device-ca-root.cert.pem"
7.	restart IoT edge runtime failed

![image](https://user-images.githubusercontent.com/35018765/69526146-83e38280-0fa4-11ea-980b-f5fa6bb5c64a.png)

**Comment by blackchoey** [comment]
File permission issue, following steps fix the error (remember to replace the user name in the commands):
1. sudo cp -r /var/lib/iotedgehubdev/certs/ /home/iotedge/chaoyitest3/
2. sudo chown -R iotedge chaoyitest3
3. update the cert path in iotedge config and restart iotedge runtime

Please try again

**Comment by czgtest** [comment]
fix work，so close it
