### ISSUE TITLE
Please make sure you\'re using an Edge device

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#244]
C:\Users\iotedge\Downloads>iotedgehubdev start -d case1.json
ERROR: (400, '{"Message":"ErrorCode:ArgumentInvalid;BadRequest","ExceptionMessage":"Tracking ID:3faf7a72bb23409dba25d6096cb5903e-G:27-TimeStamp:11/27/2019 03:29:43"} Please make sure you\'re using an Edge device.')

Expect :  Please make sure you're using an Edge device

![image](https://user-images.githubusercontent.com/35018765/69691283-8f9c8980-1109-11ea-8586-142c48a0ba7c.png)

**Comment by zunhu** [comment]
repro on Mac
1.iotedgehubdev setup -c "iotdeviceconnnectionstring"
2.iotedgehubdev start -d deployment.json

SCs-Mac-mini-2:EdgeSolution vsc$ sudo "iotedgehubdev" start -d "/Users/vsc/Documents/ChenTest/EdgeSolution/config/deployment.amd64.json" -v
ERROR: 

Expect: Please make sure you're using an edge device

**Comment by czgtest** [comment]
repro on Mac
1.iotedgehubdev setup -c "iotdeviceconnnectionstring"
2.iotedgehubdev start -d deployment.json
SCs-Mac-mini-2:EdgeSolution vsc$ sudo "iotedgehubdev" start -d "/Users/vsc/Documents/ChenTest/EdgeSolution/config/deployment.amd64.json" -v
ERROR:
Expect: Please make sure you're using an edge device

**Comment by czgtest** [comment]
also repro on ubuntu
![image](https://user-images.githubusercontent.com/35018765/69779159-0016d980-11e2-11ea-842a-0f41821ab7bf.png)

**Comment by czgtest** [comment]
fix work on windows/mac/ubuntu, so close it
