### ISSUE TITLE
create opcpublisher failed on ubuntu 

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#247]
repro on ubuntu 

case:Test host network 
1.create clean ubuntu VM with edge runtime
2. Install iotedgehubdev v0.12.0rc1 and setup device connection string
3.Use the deployment.json file as below, and make sure to replace env “_HUB_CS” with your own iothub connection string
4. Try to run command:
iotedgehubdev start -d path/to/deployment.json

![image](https://user-images.githubusercontent.com/35018765/69783201-f72c0500-11ed-11ea-96bb-82b42866c025.png)

**Comment by SLdragon** [comment]
Change image tag to 2.3 would solve the problem,

**Comment by czgtest** [comment]
fix work, so close it
