### ISSUE TITLE
use certification authority (CA) instead of CA in output message

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#253]
repro on v.0.13.0rc0

D:\iotedgehubdev>iotedgehubdev generatedeviceca
Trusted **CA** and Trusted **CA** key were not provided. Will create new trusted **CA**.
Successfully generated device **ca**. Please find the generated certs at D:\iotedgehubdev\certs

expect: Trusted certification authority (CA) and Trusted CA key were not provided. Will create new trusted CA.Successfully generated device certification authority (CA). Please find the generated certs at D:\iotedgehubdev\certs

![image](https://user-images.githubusercontent.com/35018765/70503342-27649380-1b5e-11ea-82c8-4ced3feef096.png)

**Comment by blackchoey** [comment]
Updated to `Trusted CA (certification authority) and trusted CA key were provided....` to provide information for the abbreviation. Since the abbreviation CA is widely used widely in many documents, we will keep using the abbreviation in remaining places for better readability.
