### ISSUE TITLE
transport.connect raise error (paho/mqtt/client.py)

### ISSUE THREAD

**Issue by MaheshSQL** [Azure/iotedgehubdev#259]
Hi, 

When I run the IoT Edge Simulator on Ubuntu Azure VM (VM is in a vNet) I get below error for my custom IoT Edge module.

![image](https://user-images.githubusercontent.com/20829397/70984760-01a73380-20f6-11ea-99d7-bb07373c85b6.png)

The 'iotedgehubdev' is updated to the latest version.

Interestingly, when I run the same setup and run IoT Edge simulator on another Ubuntu VM (which is not in any vNet), it runs fine and I do not get any error.

I suspect this is a security related error and would appreciate pointer from audience here to resolve it.

Thanks.

**Comment by adashen** [comment]
@MaheshSQL Thanks for reporting the issue. Can you try to add the tempSensor module (mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0) into your deployment manifest. And check whether tempSensor module could connect edgeHubDev successfully. So that we could nail down the issue to python sdk?

**Comment by MaheshSQL** [comment]
@adashen Thank you for looking into this.

I have added tempSensor module as per your suggestion and it throws below error.
![UbuntuVM_in_vNet_2](https://user-images.githubusercontent.com/20829397/71056167-387f5700-2193-11ea-8b1c-42abd1ef6c1d.png)

Hope this helps to identify the issue and resolution.

Thanks again.

**Comment by adashen** [comment]
@SLdragon Please try to reproduce the issue in Azure VM with vNet.

**Comment by MaheshSQL** [comment]
@adashen and @SLdragon, thanks for your support.

I was able to resolve this issue by including below in the deployment manifest for my custom edge module.

"createOptions": {
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host"
  }
}
