### ISSUE TITLE
[query] Is it possible to observe messges on the output endpoint during single module native debugging?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedgehubdev#262]
Is it possible to see messages emitted to output endpoint of a module with out actual logging?

**Comment by adashen** [comment]
@kiranpradeep Can you provide more detail about the scenario? There is no log configuration to turn on/off output the message from endpoints. Normally user could print the log by custom code when sending message, or consume the output message.

Another way is you could seed the message routes in edgeHubDev module with log level "verbose". The configuration is:
Add env block of edgeHub in deployment manifest like:

"env": {
     "RuntimeLogLevel": {
           "value": "verbose"
      }
}

**Comment by kiranpradeep** [comment]
Thanks for the reply. It is for use while single module native debugging. When I provide a message on input endpoint using curl command, I like to see if the module worked correctly by observing messages from the output endpoint. I will try setting verbose on RuntimeLogLevel.

**Comment by kiranpradeep** [comment]
No. That did not help. All the edgeHubDev verbose logging gives for a message is a correlationId. Neither it prints the output message nor even the output endpoint on which the message is outputted to.

Logging by writing custom code is not a satisfactory experience.

**Comment by SLdragon** [comment]
Hi, @kiranbhaga , I think for your scenario, you should add logs to your custom modules before messages send to the output. edgeHubDev by default would not log message body and output endpoint.

**Comment by kiranpradeep** [comment]
@SLdragon In-line with [comment](https://github.com/Azure/iotedgehubdev/issues/263#issuecomment-576091543) in #263, could the [iot-edge-testing-utility](https://github.com/Azure/iot-edge-testing-utility) be expanded in a future release to display messages on module output endpoints?

**Comment by SLdragon** [comment]
iot-edge-testing-utility is just a rest api server, which used to send test message, I don't think it can used to monitor module messages flow. I think you can add your own log to custom module, that's should be reasonable.

**Comment by SLdragon** [comment]
If you have any other questions, feel free to contact us, and I will close this issue, thanks!

**Comment by kiranpradeep** [comment]
@SLdragon To add, now we have a scenario in which, some modules are written by 3rd parties (different company) who will not give access to source code. They just share the docker image. Then we cannot add logs to verify if the 3rd party module is working?
