### ISSUE TITLE
TLS handshake problem

### ISSUE THREAD

**Issue by kgalic** [Azure/iotedgehubdev#266]
Hello,

We tried to deploy the OPC-UA publisher and custom module for OEE calculations and tried to use the simulator for the local testing and debugging of the custom module. 

In the logs of the custom module and OPC publisher the following errors show up:

Unhandled Exception: System.AggregateException: One or more errors occurred. (TLS authentication error.) ---> System.Security.Authentication.AuthenticationException: TLS authentication error. ---> System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

We followed the documentation for starting the simulator.

**Comment by SLdragon** [comment]
Hi, @kgalic, thanks for your feedback, we will try to repro this issue, and will let you know the result.
By the way, could you please share more information about your custom module and your deployment.json file?

**Comment by czgtest** [comment]
I create a OPCPublisher project from VSCODE marketplace and run this solution in simulator , can't repro on this issue, @kgalic  which OPCPublisher project do you use ? can you share some document about your solution? 

here is my step:
1.install edge extension in vscode
2.press F1 and run command "Azure IoT edge: new IoT edge solution"
3.select Module from Azure marketplace
4.chose OPCPublisher project and import
5.open deployment.template.json and add "_HUB_CS" env in OPCPublisher module json
![image](https://user-images.githubusercontent.com/35018765/74633825-80275c80-519d-11ea-8d95-af89e42bf948.png)

6.right-clich deployment.template.json  ,build and run IoT edge solution in simulator
here it can't repro on this issue

**Comment by kgalic** [comment]
this is what I added in the modules section of deployment.template.json:

"opcpublisher": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/iotedge/opc-publisher:latest",
              "createOptions": 
              {
                "Hostname": "publisher",
                "Cmd": [
                    "--pf=/appdata/publishednodes.json",
                    "--ns=true",
                    "--fd=true",
                    "--aa"
                ],
                "HostConfig": {
                  "Binds": [
                      "C:/Test:/appdata"
                  ]
                }
              }
            }
          },

Custom module is the default C# module generated by VSCode.

And the problem might be in not adding _HUB_CS. Is this obligatory for every module? Where exactly you get that connection string from?

**Comment by SLdragon** [comment]
Hi, @kgalic, from your error message, it seems not related to the connection string but related to the cert validation. Which sytem do you use to run this module?

PS: if you want to get IoT Hub connection string, you can follow the link to copy IoT Hub connection string from Azure Portal

**Comment by czgtest** [comment]
@kgalic   I use your provided opcpublisher json and run in simulator on Windows10,  Can't repro this issue, Can you share your project for us ?

here is my step:
1.install edge extension in vscode
2.press F1 and run command "Azure IoT edge: new IoT edge solution"
3.select C# module
4.open deployment.template.json and add  your provided opcpublisher json
`"opcpublisher": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/iotedge/opc-publisher:latest",
              "createOptions": 
              {
                "Hostname": "publisher",
                "Cmd": [
                    "--pf=/appdata/publishednodes.json",
                    "--ns=true",
                    "--fd=true",
                    "--aa"
                ],
                "HostConfig": {
                  "Binds": [
                      "C:/Test:/appdata"
                  ]
                }
              }
            },
            "env": {
              "_HUB_CS": {
                  "value": "IoT Hub Connection string"
              }
          }
          }`
5.right-clich deployment.template.json  ,build and run IoT edge solution in simulator
6.docker  will  reminder user to  share "C:/Test:/appdata" folder,  click yes 
here it can't repro on this issue

**Comment by kgalic** [comment]
[EdgeTest.zip](https://github.com/Azure/iotedgehubdev/files/4221885/EdgeTest.zip)

**Comment by czgtest** [comment]
@kgalic  I try your project on Windows10  PC,  can't find TLS authentication error,  do you run this module on Mac ?  if yes, it has cert issue #30 when debug C# module , and has a  workaround provided [here ](https://github.com/Azure/iotedgehubdev/issues/30).

**Comment by kgalic** [comment]
That is good to know, thank you. For this occasion, I used Win 10 PC.

**Comment by SLdragon** [comment]
Hi, @kgalic , from the error message, seems that it is related to the certificate, so maybe you can try this below:

1. Remove the iotedgehubdev config folder in "C:\ProgramData\iotedgehubdev"
2. Re-setup iotedgehubdev in the vscode through command palette "Azure IoT Edge: Set up IoT Edge simulator"

If the above not works, try different version of the package "Microsoft.Azure.Devices.Client" in the "modules/SampleModule/SampleMoudule.csproj"

```
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*" />
```

**Comment by kgalic** [comment]
I removed everything from iotedgehubdev and SampleModule now works. However, opc publisher is still struggling to pick up the module connection string and I am getting the following error:

```
Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
opcpublisher    | [17:15:33 FTL]    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 157
opcpublisher    |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 62
opcpublisher    |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\Program.cs:line 742
opcpublisher    | System.ArgumentException: Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
opcpublisher    |    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 157
opcpublisher    |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 62
opcpublisher    |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\Program.cs:line 742
opcpublisher    | [17:15:33 FTL] Publisher exiting...
```
Even after adding _HUB_CS to env, and trying with normal device connection string, and module connection string.

**Comment by SLdragon** [comment]
Hi, @kgalic, you should use IoT Hub connection string for _HUB_CS, here are some documents: https://github.com/Azure/iot-edge-opc-publisher/tree/master#command-line-options

**Comment by junsaw** [comment]
@SLdragon thanks alot for the assistance.  For anyone else who is experiencing this issue and are using Docker Desktop for Windows as part of their development work-space. This is as a result of a time drift between the VM used  for Linux containers on Windows machines:

The following commands can be used to sync the time between the Host Machine and the VM: 

Get-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization" | Disable-VMIntegrationService
Get-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization" | Enable-VMIntegrationService

You can also toggle this setting in the Hyper-V UI by going to the VM settings -> Integration Services -> Time Synchronization. 

I hope this help others who are facing the similar issue.
