### ISSUE TITLE
Can't install version 0.13.0 on Python 3.8.2

### ISSUE THREAD

**Issue by fgsantos89** [Azure/iotedgehubdev#272]
Documentation says this package supports Python 3.8 but when installing the last version with this command on Ubuntu 20.04:
sudo pip3 install iotedgehubdev==0.13.0

Give this error:
ERROR: Package 'iotedgehubdev' requires a different Python: 3.8.2 not in '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <=3.8'

**Comment by SLdragon** [comment]
Thank you for your feedback, we will fix this issue in the next release

**Comment by SLdragon** [comment]
@fgsantos89 , the issue has been fixed in 0.14.0, please take a try, thank you!

**Comment by fgsantos89** [comment]
Thanks, it's working. :smile:
