### ISSUE TITLE
Build and Run IoT Edge Solution in Simulator fails on LODS VM environment

### ISSUE THREAD

**Issue by darenm** [Azure/iotedgehubdev#281]
When attempting to build a custom IoT Edge c# module using the VS Code IoTEdge extension within the Learning On Demand (LODS) virtual environment, the command fails with the following error message:

Error
```
"/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev" setup -c "HostName=iot-az220-training-dm20200803.azure-devices.net;DeviceId=SimulatedDevice;SharedAccessKey=<removed-key>=" -i "HostName=iot-az220-training-dm20200803.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<removed-key>"
authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$ "/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev" setup -c "HostName=iot-az220-training-dm20200803.azure-devices.net;DeviceId=SimulatedDevice;SharedAccessKey=<removed-key>" -i "HostName=iot-az220-training-dm20200803.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<removed-key>"
bash: /mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev: No such file or directory
authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$
```

The LODS VM has the following installed:

* WIndows 10 2004 19041.329
* Python 3.8.5
* pip installed iotedgehubdev 1.14.1
* Docker version 19.03.12
* WSL 2 running
  * Legacy V1
  * docker-desktop-data V2
  * docker-desktop V2
* Visual Studio Code 1.47.3
  * Extensions:
     * Azure IoT Tools v0.3.0 including Azure IoT Edge v1.22.0
     * C# 1.22.1

The Lab Instructions that are being followed are documented at: https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Instructions/Labs/LAB_AK_13-deploy-and-debug-custom-azure-iot-edge-module.html#exercise-1-verify-lab-prerequisites

**Comment by darenm** [comment]
I executed the lab in an ExpressLabs virtual environment and the command executed OK - I noticed that in this environment the `iotedgehubdev` command is executed using PowerShell rather than bash. The environment has different versions of Python and Docker:
* Python - 3.7.6
* Docker version 19.03.5

**Comment by SLdragon** [comment]
same with the issue here: https://github.com/microsoft/vscode-azure-iot-edge/issues/556

**Comment by konichi3** [comment]
microsoft/vscode-azure-iot-edge#556 is closed. Closing
