### ISSUE TITLE
ConnectionString not available for Edge device provisioned with X509

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedgehubdev#282]
Im not able to run the below command

```
sudo iotedgehubdev setup -c "<edge-device-connection-string>"
```
As my edge device was provisioned with DPS using X509 and there no connection string available for that case.  Let me know how can i generate the connection string for edge device

And if i use below connection string:

```
"HostName=iot-platform-develop-iothub.azure-devices.net;DeviceId=amidha;x509=true"
```

using command

```
iotedgehubdev setup -c "HostName=iot-platform-develop-iothub.azure-devices.net;DeviceId=amidha;x509=true"
```

The error I get is 

```
ERROR: 'Error parsing connection string. Please make sure you wrap the connection string with double quotes when supplying it via CLI'
```

**Comment by SLdragon** [comment]
Can you access the azure portal of IoT Hub? If so, you can get the edge device connection string here.

If you cannot access the azuere portal but you have the iothub connection string, you can use Azure IoT Tools in the VSCode to manage the device. For more information, please check this url: 
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-tools
