### ISSUE TITLE
[0.14.3] does not install

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/iotedgehubdev#291]
You closed issue #288 
But I tried `pip install --upgrade iotedgehubdev` and still get 0.14.2

I tried removing and reinstalling the Azure IoT Edge Tools extension, but did not help

I finally tried `pip install --upgrade setuptools` but NADA

Please explain how to install 0.14.3

Thank you

**Comment by dvescovi1** [comment]
I can also confirm @uriel-kluk findings. Both Visual Studio 2019 Extension and Visual Studio Code are still unusable as they unconditionally install iotedgehubdev which seems to pulls 0.14.2 no matter what.

**Comment by konichi3** [comment]
The root cause was resolved in version 0.14.3 of iotedgehubdev Azure/iotedgehubdev#288. If you are still experiencing the same symptoms, please update this thread.

**Comment by konichi3** [comment]
Closing the issue. Please let us know if this still reproduces
