### ISSUE TITLE
python edge module errors in simulator.

### ISSUE THREAD

**Issue by Rumpkie** [Azure/iotedgehubdev#296]
I am developing on a Mac and I am having the following Error when I fire up my python module:

Traceback (most recent call last):
timerMonitor    |   File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
timerMonitor    |     self.transport.connect(password=self.sas_token)
timerMonitor    |   File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
timerMonitor    |     raise exceptions.ConnectionFailedError(cause=e)
timerMonitor    | azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'. (_ssl.c:1091)
timerMonitor    | 
timerMonitor    | ConnectOperation: completing with error None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'. (_ssl.c:1091)
timerMonitor    | RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'. (_ssl.c:1091).  Setting timer.

**Comment by marianan** [comment]
Thanks for reporting this issue. Could you please share more details about your exact repro steps?

**Comment by konichi3** [comment]
@Rumpkie
It would be good if you can provide additional detail and repro steps.

**Comment by marianan** [comment]
Hello @Rumpkie, I am closing this issue as we have not heard back on the repro steps for this issue. If the symptoms persist or you have any questions, please feel free to reopen the issue.
