### ISSUE TITLE
edgeHubDev Processing pending subscriptions for module: Exhausted Iot hub Daily messages quota

### ISSUE THREAD

**Issue by gopimails** [Azure/iotedgehubdev#302]
I have EdgeHub Dev with vscode for my development and is connected to IoT hub. I was all working good; but today I did a docker system prune volume to free some space.

Post that, when I am running(build and run IoT Edge solution in simulator) the solution, receving
**edgeHubDev  | <6> 2021-01-16 23:35:21.575 +00:00 [INF] - Processing pending subscriptions for myedgedevice/mymodule1
edgeHubDev   | <6> 2021-01-16 23:35:21.589 +00:00 [INF] - Processing pending subscriptions for myedgedevice/mymodule2**

I am getting this continuously for all my modules and is never ending exhausting Iot hub Daily messages quota.

Not sure what could have gone wrong!!

**Comment by marianan** [comment]
Hello @gopimails , thanks for posting your question. Two questions:
1. Could you please try to deploy your modules to a real device and let us know if the issue persists? 
2. Could you please share full log for us to investigate, these 2 lines unfortunately are not sufficient for root causing.

**Comment by konichi3** [comment]
We are closing this issue for now. Feel free to reach back if you experience the same symptom
