### ISSUE TITLE
iotedgedev.exe flagged as malware in Cylance

### ISSUE THREAD

**Issue by rodavrow** [Azure/iotedgehubdev#303]
Our corporate anti-virus Cylance is flagging iotedgedev.exe as malware.
VirusTotal and JoeSandbox are also reporting it as malware:

https://www.virustotal.com/gui/file/def966125bd2aca5a41bcbb580d1bb999f73cc7326f9d3eb46dd6834bf79693e/detection

Probably a false positive again, but we cannot just whitelist it until sure. Can the root cause be found and resolved? Thanks!

**Comment by marianan** [comment]
Thank you for reporting this issue, we are looking into the issue and will get back to the thread once we have any details.

**Comment by konichi3** [comment]
@rodavrow 

Unfortunately, we are unable to root cause the issue at this time. Would whitelist be a permanent workaround that you can use or is this blocking?

**Comment by smcd253** [comment]
@rodavrow we have addressed this issue and have updated the problematic dependencies and our pypi package.

https://pypi.org/project/iotedgehubdev/
`pip install iotedgehubdev==0.14.5`

Please rerun your tests with this new package and let us know if you are still having any issues.

**Comment by HenrikDamslund** [comment]
This is still an issue with 0.14.5 - Micsoft Defender detected iotedgehubdev.exe as 'Trojan:Win32/Zpevdo.B'

**Comment by smcd253** [comment]
Hi @HenrikDamslund ,
Please follow the steps outlined here: https://github.com/Azure/iotedgehubdev/issues/274#issuecomment-812644362 to refresh Defender.

**Comment by marianan** [comment]
Closing this issue as the symptoms no longer manifest.
