### ISSUE TITLE
Can't run setup command: Error parsing string

### ISSUE THREAD

**Issue by RaiseYourChicken** [Azure/iotedgehubdev#307]
![image](https://user-images.githubusercontent.com/18746685/107561994-24888700-6bd7-11eb-814a-3a4c7b0e2431.png)

I tried this with both a pip installation (python2.7) and a pip3 installation (python3.6), in both cases I get the same message error. Any clues where this can come from, I searched on google for quite some time but there's very few information about azure edge.

**Comment by marianan** [comment]
Hello @RaiseYourChicken thanks for reporting this issue. -c parameter supplies a connection string and the string "undefined" in your example does not meet the syntax requirements for a connection string. Please refer to the Quickstart section of this repo for getting started with iotedgehubdev tool.
