### ISSUE TITLE
Not able to receive Twin Property Updates

### ISSUE THREAD

**Issue by XavierGeerinck** [Azure/iotedgehubdev#309]
Hi There!

I am currently trying to work with Twin Updating but am being unsuccessful. Would anyone know which steps I should follow for this? Is the simulator supporting C2D messages with Twin Property updates? :)

**Comment by marianan** [comment]
Hi @XavierGeerinck thanks for reporting your issue. Could you please share detailed repro steps? C2D messages are supported. I would guess that there may be issues with the routes definition if the messages aren't arriving as expected.

**Comment by XavierGeerinck** [comment]
Hi @marianan I have opened another issue for the Python SDK with more details, is it ok if I link to this one? (https://github.com/Azure/azure-iot-sdk-python/issues/737).

I tried starting with the `iotedgehubdev` (both tried bundled vscode version and standalone installation) and the `iotedgedev` dev container both none of them are receiving C2D messages with the updated Twin Properties.

**Comment by marianan** [comment]
Hi @XavierGeerinck , I am not sure of the correct callback to listen on (the SDK question) but the simulator doesn't have any known limitations. If you run on a VM or real device, do you see the same behavior?

**Comment by XavierGeerinck** [comment]
Hi @marianan thanks a lot for your response! I am currently assuming it is the SDK seeing that the event is simply not arriving, it seems that the SDK team is investigating this.  Would it make sense to utilize that issue as the main one?

**Comment by marianan** [comment]
Hi @XavierGeerinck thanks for confirming. I am closing this issue here. Once the python SDK issue is resolved, feel free to file a new issue here if you experience the same symptoms.
