### ISSUE TITLE
ERROR: the JSON object must be str, bytes or bytearray, not dict

### ISSUE THREAD

**Issue by bet2019** [Azure/iotedgehubdev#346]
1. i used the command "iotedgehubdev start -d ", but facing below issue.
![Capture](https://user-images.githubusercontent.com/57758819/130448546-0c9903dc-eecb-40b4-aefa-9a81d08a8033.JPG)

2. when >iotedgehubdev start -i single model, how can i debug my code. i sent messages by curl, where i can see the result?

**Comment by marianan** [comment]
Hello @bet2019, when using the -d option, please point to the deployment manifest file and not the template. The deployment manifest file is generated after you build your module and is typically located in the config folder, for example config/deployment.amd64.json. 
To debug your IoT Edge module using the simulator, please use the steps at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11#build-and-debug-a-single-module

**Comment by bet2019** [comment]
@marianan 
thank you! that's right, i need point to deployment manifest in config folder.
For start and debug single module natively. [https://github.com/Azure/iotedgehubdev#3-start-and-debug-a-single-module-natively](url)
step 2. Output the module credential environment variables. iotedgehubdev modulecred.
I exported the credentials, but do not know where to use it.

**Comment by marianan** [comment]
This is all wrapped up VS/VSCode extension so you don't need to worry about the modulcred step. Is your breakpoint hit when you follow the steps in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11#build-and-debug-a-single-module?

**Comment by bet2019** [comment]
@marianan 
thank you!
but, my teams facing this kind of issue. IOTEDGE_WORKLOADURI required. not know where missing configuration at all.
could you help what heppening? appreciate it.
![1](https://user-images.githubusercontent.com/57758819/130568017-f3a060e9-bd7d-49b2-b39f-7e09c5e5ae7b.png)
![2](https://user-images.githubusercontent.com/57758819/130568021-2f27f980-d6c7-4b7f-a694-111e223038c2.png)

**Comment by marianan** [comment]
@bet2019 just to confirm are you able to build and debug a single Edge module in VS/VSCode as indicated in this walkthrough? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11#build-and-debug-a-single-module

I would like to make sure the original issue is resolved before looking into the workload uri one. Please file a new issue to tackle debugging the EdgeControllerAgent Edge module - we would need to know more about the functionality/scenarios of this module which is deferent than the default generated Edge module.

**Comment by bet2019** [comment]
For me, it is solved, close this one.

在 2021-08-25 01:36:42，"Mariana Mihova" ***@***.***> 写道：


@bet2019 just to confirm are you able to build and debug a single Edge module in VS/VSCode as indicated in this walkthrough? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11#build-and-debug-a-single-module

I would like to make sure the original issue is resolved before looking into the workload uri one. Please file a new issue to tackle debugging the EdgeControllerAgent Edge module - we would need to know more about the functionality/scenarios of this module which is deferent than the default generated Edge module.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
