### ISSUE TITLE
Please make sure you're using an Edge Device

### ISSUE THREAD

**Issue by davidguidali** [Azure/iotedgehubdev#348]
I get this error message when trying to build a new iot edge project.

![image](https://user-images.githubusercontent.com/61904428/131559813-967df4ce-7485-4dd6-a17a-eb3b61047801.png)

I have no clue where this is coming from, I can create a completely new project, setup the iotedgehubdev simulator but still the error occurs. 
I am using the most recent version of Docker & the simulator..

**Comment by davidguidali** [comment]
My fault, soon after writing this post I found out that i used the connection string of a "iot device" instead of a "iot edge device". Stupid me!

**Comment by mhshami01** [comment]
Hello @davidguidali,

Thank you for your interest in using the simulator. Please ensure that:
   - you have setup and IoT Hub and registered an IoT Edge Device (The first two steps of this [quick start using az cli](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-2018-06)
   - obtain the connection string to the registered edge device as shown in the quick start from the previous step, and
   - prepare the simulator using the command 'iotedgehubdev setup -c "<edge-device-connection-string>"' as specified in the setup section of the [README.md](https://github.com/Azure/iotedgehubdev/blob/master/README.md)
