### ISSUE TITLE
GetTwinAsync() are not supported in IoT edge Simulator v0.14.10

### ISSUE THREAD

**Issue by HajKasemIbrahim** [Azure/iotedgehubdev#354]
GetTwinAsync() returns always Twin object with empty properties, all properties of my IoT edge module are null when I run my IoT edge device in Simulator, in my Linux server works everything fine. I should wait also about 20 seconds to get a response from GetTwinAync()

**Comment by marianan** [comment]
@HajKasemIbrahim thank you for this report. I was able to reproduce it and this behavior appears to be by design based on this [answer](https://stackoverflow.com/a/67215378).
