### ISSUE TITLE
Latest release considered unsafe by Microsoft Defender SmartScreen

### ISSUE THREAD

**Issue by IGx89** [Azure/iotedgehubdev#355]
Trying to download the zip of the latest release (0.14.10) is blocked by Microsoft Defender SmartScreen:

![image](https://user-images.githubusercontent.com/282698/140414759-33f4fd62-7349-44db-9706-441932356aad.png)

A side effect is that the IoT Edge extension for VS Code, which downloads that zip file on Windows, hits the same issue and silently fails for us (due to a company security app that apparently also pulls from the SmartScreen list).

Might not be anything you can do about it, but since you're also Microsoft I thought I'd report it just in case :). The 0.14.9 zip is just fine.

**Comment by marianan** [comment]
Thanks @IGx89 for reporting this issue. We are investigating.

**Comment by marianan** [comment]
@IGx89 - are you still experiencing the issue? Earlier in the week there was an outage in one of the MS Defender services that has been resolved. Please make sure to restart the device to ensure that no previous reputations are cached.

**Comment by IGx89** [comment]
It's half better now: Edge doesn't block the download, but our company's security tool (Palo Alto Cortex XDR) is still blocking the executable from running. Guessing there's nothing you can do/know about that tool?

**Comment by IGx89** [comment]
We ended up having to manually add the hash of the executable to Cortex's allow list -- that solved it.
