### ISSUE TITLE
Iotedgehubdev not working under Zscaler.

### ISSUE THREAD

**Issue by LanceLiMS** [Azure/iotedgehubdev#358]
Cx from Fonterra would like to debug iotedge module using iotedgehubdev tool within their company network env.
Fonterra has been moving to an application called Zscaler to run its traffic through the proxy. We confirmed that:
**Ordinary IoT simulated device is able to connect to IoT Hub (MQTT) under this kind of networking config**, which means iothub host and 443/8883 port are not blocked by their firewall.
But the sample module could not connect to IoT Hub when we start the iotedge simulator (Downstreamprotocol: AmqpWS).

We are wondering if iotedgedevhub works with Zscaler proxy and SSL inspection.

Here's the edgeHub logs we collected:

**edgeHub logs:**

> Executing task: docker logs --tail 1000 -f 35dafd0b5b6dac2bee52a3bbf80616807cb54da1f46f4fa1f6d3c3000230fa63
2021-11-18 02:03:06 Starting Edge Hub
Nov 18 02:03:06.306 INFO watchdog: Starting Watchdog
Nov 18 02:03:06.307 INFO watchdog: Registering shutdown signal listener
Nov 18 02:03:06.311 INFO watchdog: MQTT broker is disabled
Nov 18 02:03:06.311 INFO watchdog::child: Launched Edge Hub process with pid 9
2021-11-18 02:03:06.810 +00:00 Edge Hub Main()
<6> 2021-11-18 02:03:07.877 +00:00 [INF] - Installing certificates [CN=Edge Agent CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:10/03/2022 03:10:39],[CN=Edge Test Device CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:10/04/2022 03:10:34] to Root
<6> 2021-11-18 02:03:08.022 +00:00 [INF] - Installing certificates to Root
<6> 2021-11-18 02:03:08.038 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
<6> 2021-11-18 02:03:09.550 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false,"EnableMqttBroker":false}
<6> 2021-11-18 02:03:11.043 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2021-11-18 02:03:11.154 +00:00 [INF] - Created device scope identities cache
<6> 2021-11-18 02:03:11.189 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2021-11-18 02:03:11.414 +00:00 [INF] - Initializing Edge Hub
<6> 2021-11-18 02:03:11.415 +00:00 [INF] -
█████╗ ███████╗██╗ ██╗██████╗ ███████╗
██╔══██╗╚══███╔╝██║ ██║██╔══██╗██╔════╝
███████║ ███╔╝ ██║ ██║██████╔╝█████╗
██╔══██║ ███╔╝ ██║ ██║██╔══██╗██╔══╝
██║ ██║███████╗╚██████╔╝██║ ██║███████╗
╚═╝ ╚═╝╚══════╝ ╚═════╝ ╚═╝ ╚═╝╚══════╝
 ██╗ ██████╗ ████████╗ ███████╗██████╗ ██████╗ ███████╗
██║██╔═══██╗╚══██╔══╝ ██╔════╝██╔══██╗██╔════╝ ██╔════╝
██║██║ ██║ ██║ █████╗ ██║ ██║██║ ███╗█████╗
██║██║ ██║ ██║ ██╔══╝ ██║ ██║██║ ██║██╔══╝
██║╚██████╔╝ ██║ ███████╗██████╔╝╚██████╔╝███████╗
╚═╝ ╚═════╝ ╚═╝ ╚══════╝╚═════╝ ╚═════╝ ╚══════╝
<6> 2021-11-18 02:03:11.430 +00:00 [INF] - Version - 1.2.6.48918552 (e15b86b2783d64b6136b15fcd09e3584269c3be1)
<6> 2021-11-18 02:03:11.431 +00:00 [INF] - OptimizeForPerformance=True
<6> 2021-11-18 02:03:11.431 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2021-11-18 02:03:11.460 +00:00 [INF] - Loaded server certificate with expiration date of "2022-10-02T03:10:40.0000000+00:00"
<6> 2021-11-18 02:03:11.565 +00:00 [INF] - Using Asp Net server for metrics
<6> 2021-11-18 02:03:11.767 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2021-11-18 02:03:11.771 +00:00 [INF] - Created new message store
<6> 2021-11-18 02:03:12.178 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2021-11-18 02:03:12.281 +00:00 [INF] - Initialized storing twin manager
<6> 2021-11-18 02:03:12.371 +00:00 [INF] - Add node: mydevice2/$edgeHub
<6> 2021-11-18 02:03:12.372 +00:00 [INF] - Initializing configuration
<6> 2021-11-18 02:03:13.040 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2021-11-18 02:03:13.074 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false,"EnableMqttBroker":false}
<6> 2021-11-18 02:03:13.442 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2021-11-18 02:03:13.657 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2021-11-18 02:03:13.657 +00:00 [INF] - r1: FROM /messages/modules/SampleModule/outputs/* INTO $upstream
<6> 2021-11-18 02:03:13.657 +00:00 [INF] - r2: FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/SampleModule/inputs/input1")
<6> 2021-11-18 02:03:13.667 +00:00 [INF] - Updated message store TTL to 922337203685.4775 seconds
<6> 2021-11-18 02:03:13.668 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2021-11-18 02:03:13.711 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2021-11-18 02:03:13.712 +00:00 [INF] - Initialized edge hub configuration
<6> 2021-11-18 02:03:13.751 +00:00 [INF] - Scheduling server certificate renewal for "2022-10-02T03:08:10.0003994Z".
<6> 2021-11-18 02:03:13.754 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2021-11-18 02:03:13.771 +00:00 [INF] - Starting MQTT head
<6> 2021-11-18 02:03:13.886 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2021-11-18 02:03:14.067 +00:00 [INF] - Starting AMQP head
<6> 2021-11-18 02:03:14.101 +00:00 [INF] - Started MQTT head
<6> 2021-11-18 02:03:14.548 +00:00 [INF] - Started AMQP head
<6> 2021-11-18 02:03:14.552 +00:00 [INF] - Starting HTTP head
<6> 2021-11-18 02:03:14.736 +00:00 [INF] - Unable to authenticate client mydevice2/SampleModule with cached service identity mydevice2/SampleModule (Found: False). Resyncing service identity...
<4> 2021-11-18 02:03:14.777 +00:00 [WRN] - Error while refreshing the service identity: mydevice2/SampleModule OnBehalfOf: mydevice2
System.Collections.Generic.KeyNotFoundException: The given key 'mydevice2/SampleModule' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentityInternal(String refreshTarget, String onBehalfOfDevice, Boolean invokeServiceIdentitiesUpdated) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 187
<4> 2021-11-18 02:03:15.331 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2021-11-18 02:03:15.353 +00:00 [INF] - Started HTTP head
<6> 2021-11-18 02:03:16.221 +00:00 [INF] - New token received on the Cbs link
<6> 2021-11-18 02:03:16.504 +00:00 [INF] - Unable to authenticate client mydevice2/SimulatedTemperatureSensor with cached service identity mydevice2/SimulatedTemperatureSensor (Found: False). Resyncing
service identity...
<4> 2021-11-18 02:03:16.506 +00:00 [WRN] - Error while refreshing the service identity: mydevice2/SimulatedTemperatureSensor OnBehalfOf: mydevice2
System.Collections.Generic.KeyNotFoundException: The given key 'mydevice2/SimulatedTemperatureSensor' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentityInternal(String refreshTarget, String onBehalfOfDevice, Boolean invokeServiceIdentitiesUpdated) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 187
<6> 2021-11-18 02:03:17.864 +00:00 [INF] - Closing link Events for mydevice2/SimulatedTemperatureSensor
<4> 2021-11-18 02:03:19.597 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
<6> 2021-11-18 02:03:19.600 +00:00 [INF] - Retry refreshing device scope identities cache. Waiting for 60 seconds.
<6> 2021-11-18 02:03:19.604 +00:00 [INF] - Device scope identities refresh is ready because a refresh was signalled.
<6> 2021-11-18 02:03:19.604 +00:00 [INF] - Starting refresh of device scope identities cache
Nov 18 02:03:24.755 INFO watchdog: Watchdog received SIGTERM signal
Nov 18 02:03:25.327 INFO watchdog::child: Terminating Edge Hub process
Nov 18 02:03:25.327 INFO watchdog::child: Sending SIGTERM signal to Edge Hub process
<6> 2021-11-18 02:03:25.330 +00:00 [INF] - Termination requested, initiating shutdown.
<6> 2021-11-18 02:03:25.332 +00:00 [INF] - Stopping the protocol heads...
<6> 2021-11-18 02:03:25.333 +00:00 [INF] - Closing protocol heads - (MQTT, AMQP, HTTP)
<6> 2021-11-18 02:03:25.335 +00:00 [INF] - Stopping
<6> 2021-11-18 02:03:25.348 +00:00 [INF] - Closing HTTP head
<6> 2021-11-18 02:03:25.359 +00:00 [INF] - Waiting for cleanup to finish
<6> 2021-11-18 02:03:25.363 +00:00 [INF] - Closed HTTP head
<4> 2021-11-18 02:03:25.767 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
<6> 2021-11-18 02:03:25.767 +00:00 [INF] - Retry refreshing device scope identities cache. Waiting for 60 seconds.
<6> 2021-11-18 02:03:25.768 +00:00 [INF] - Device scope identities refresh is ready because a refresh was signalled.
<6> 2021-11-18 02:03:25.768 +00:00 [INF] - Starting refresh of device scope identities cache
<4> 2021-11-18 02:03:30.990 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
<6> 2021-11-18 02:03:30.994 +00:00 [INF] - Retry refreshing device scope identities cache. Waiting for 60 seconds.
<6> 2021-11-18 02:03:30.996 +00:00 [INF] - Device scope identities refresh is ready because a refresh was signalled.
<6> 2021-11-18 02:03:30.999 +00:00 [INF] - Starting refresh of device scope identities cache
Terminal will be reused by tasks, press any key to close it.<

**Sample Module logs**
> Executing task: docker logs --tail 1000 -f 622e4d47ea70c12b1dd46a9cce47fcf72085fecf7d422ebdd005c51af56de088 <
IoT Hub Client for Python
Subscribe for input failed. Not enabling feature
./main.py:36: RuntimeWarning: coroutine 'execute_patch_for_async.<locals>.shutdown' was never awaited
client.shutdown()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 396, in connect
host=self._hostname, port=8883, keepalive=self._keep_alive
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
raise err
File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
return await callback.completion()
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
return await self.future
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
self.transport.connect(password=password)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 418, in connect
raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by ConnectionRefusedError(111, 'Connection refused')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./main.py", line 79, in <module>
main()
File "./main.py", line 55, in main
client = create_client()
File "./main.py", line 33, in create_client
client.on_message_received = receive_message_handler
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 740, in on_message_received
self._generic_receive_handler_setter("on_message_received", constant.INPUT_MSG, value)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 483, in _generic_receive_handler_setter
fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
return self.__get_result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 106, in _enable_feature
await handle_result(callback)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 37, in handle_result
raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)
Task was destroyed but it is pending!
task: <Task pending coro=<AsyncHandlerManager._receiver_handler_runner() running at /usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_handler_manager.py:43> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7fbc1fe001d0>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<_AsyncQueueProxy.get() running at /usr/local/lib/python3.7/site-packages/janus/__init__.py:451> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc1fe00dd0>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
IoT Hub Client for Python
Subscribe for input failed. Not enabling feature
./main.py:36: RuntimeWarning: coroutine 'execute_patch_for_async.<locals>.shutdown' was never awaited
client.shutdown()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 396, in connect
host=self._hostname, port=8883, keepalive=self._keep_alive
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
raise err
File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
return await callback.completion()
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
return await self.future
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
self.transport.connect(password=password)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 418, in connect
raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by ConnectionRefusedError(111, 'Connection refused')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./main.py", line 79, in <module>
main()
File "./main.py", line 55, in main
client = create_client()
File "./main.py", line 33, in create_client
client.on_message_received = receive_message_handler
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 740, in on_message_received
self._generic_receive_handler_setter("on_message_received", constant.INPUT_MSG, value)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 483, in _generic_receive_handler_setter
fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
return self.__get_result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 106, in _enable_feature
await handle_result(callback)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 37, in handle_result
raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)
Task was destroyed but it is pending!
task: <Task pending coro=<AsyncHandlerManager._receiver_handler_runner() running at /usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_handler_manager.py:43> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f02d731a1d0>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<_AsyncQueueProxy.get() running at /usr/local/lib/python3.7/site-packages/janus/__init__.py:451> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f02d731add0>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
IoT Hub Client for Python
ReconnectStage: DisconnectEvent received while in unexpected state - LOGICALLY_DISCONNECTED, Connected: False
Subscribe for input failed. Not enabling feature
./main.py:36: RuntimeWarning: coroutine 'execute_patch_for_async.<locals>.shutdown' was never awaited
client.shutdown()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
return await callback.completion()
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
return await self.future
azure.iot.device.common.pipeline.pipeline_exceptions.OperationCancelled: OperationCancelled('Transport timeout on connection operation')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./main.py", line 79, in <module>
main()
File "./main.py", line 55, in main
client = create_client()
File "./main.py", line 33, in create_client
client.on_message_received = receive_message_handler
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 740, in on_message_received
self._generic_receive_handler_setter("on_message_received", constant.INPUT_MSG, value)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 483, in _generic_receive_handler_setter
fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
return self.__get_result()
File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 106, in _enable_feature
await handle_result(callback)
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 55, in handle_result
raise exceptions.OperationCancelled(message="Could not complete operation", cause=e)
azure.iot.device.exceptions.OperationCancelled: OperationCancelled('Could not complete operation') caused by OperationCancelled('Transport timeout on connection operation')
Task was destroyed but it is pending!
task: <Task pending coro=<AsyncHandlerManager._receiver_handler_runner() running at /usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_handler_manager.py:43> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7fe149f2e210>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<_AsyncQueueProxy.get() running at /usr/local/lib/python3.7/site-packages/janus/__init__.py:451> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe149f2ee10>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
Terminal will be reused by tasks, press any key to close it.

**Comment by marianan** [comment]
@LanceLiMS thank you for reporting this issue, we are investigating

**Comment by mhshami01** [comment]
Hello @LanceLiMS,

We suspect that ZScaler is interfering in two ways:
1- with the trust chain, see https://help.zscaler.com/zia/about-ssl-inspection
2- the docker network bridge, see https://docs.docker.com/network/proxy/

The simulator uses docker containers to launch an instance of the IoT Edge Runtime and for debugging modules. In addition,
it stands up a docker network bridge (azure-iot-edge-dev) to facilitate communication between the containers.

When the simulator launches the Runtime, it sets up a chain of trust by way of an authority and two certificates - hubserver and edge device. See https://github.com/Azure/iotedgehubdev/blob/master/iotedgehubdev/edgemanager.py - line 254. The certificates are copied from C:\ProgramData\iotedgehubdev\data\certs\ on the host machine to '/var/lib/iotedgehubdev/certs' inside the Runtime container.

Sincerely,
--H

**Comment by LanceLiMS** [comment]
Hi @mhshami01 
Thanks a lot for your reply.
I also noticed in a similar stackoverflow question: [https://stackoverflow.com/questions/67128617/zscaler-ssl-inspection-proxy-solution-for-iot-edge](url)
There's an answer related to iotedge runtime:
“You will need the Zscaler root certificate added to list of root certificates that are trusted by OpenSSL in both the edgeAgent and edgeHub modules. Without that the TLS negotiation will fail with not trusting the certificate chain from any server that they attempt to negotiation a TLS connection with.”
Customer does have a Zscaler root certficate and moved it to the specified directories but it did not appear to get him any further.
One question here is that how should make the Zscaler root certificate added to list of root certificates that are trusted by OpenSSL in both the edgeAgent and edgeHub modules when using iotedgehubdev? Thanks in advance!

**Comment by mhshami01** [comment]
Hello @LanceLiMS,

The simulator provides a command to enable the use of a custom CA for authentication. Please consider trying 'IoTEdgeHubDev generatedeviceca --trusted-ca'.

For more info, see 'IoTEdgeHubDev generatedeviceca -h'

Thank you,
--H

**Comment by konichi3** [comment]
@LanceLiMS

Happy new year! Were you able to resolve the issue?

**Comment by marianan** [comment]
Closing the thread, please reach back if you have any questions.
