### ISSUE TITLE
Iotedgehub not taking environments from solution into consideration when running in Visual Studio 2019

### ISSUE THREAD

**Issue by sandervanteinde** [Azure/iotedgehubdev#359]
This is a slight dupe of #265 , but since that issue was closed I will create a new one.

In that issue a lot of steps were described that were taken into consideration, none of them worked. I recommend reading through them for an entire picture.

My situation is as follows and is not working:

I am running it through Visual Studio 2019 using the following extension: https://marketplace.visualstudio.com/items?itemName=vsc-iot.vs16iotedgetools.

When running the solution, none of the solutions provided in #265 were working for me.
I have tried all solutions provided there.

**Repro steps**
I have created a reproduction repo for your convenience. Steps to reproduce:
1. Startup the solution AzureIotEdgeApp1.sln from the repo using the latest Visual Studio 2019.
2. Ensure that the "AzureIotEdgeApp1" project is selected as startup project
3. Hit the start debugging button in Visual Studio.
4. The expected value should be "Hello MyVar", but instead the string "MYVAR was not set 🤔" was printed.

**Expected behaviour**
One of the following:
1. When running from Visual Studio 2019, I expect it to take the launchSettings.json file into consideration. This describes how my app launches when running from Visual Studio and contains the correct environment variables
2. When running from Visual Studio 2019, I expect it to take the deployment.debug.template.json environment variables into consideration when launching the dotnet host for the project that is being run outside of the docker environment.

**Edit**: And ofcourse the link to the repo: https://github.com/sandervanteinde/sample-iotedge-app-not-working

**Comment by sandervanteinde** [comment]
The solution of described in #265 by @mikanyg worked. we unfortunately nested the object 1 level deeper and than it doesn't work.

**Comment by mhshami01** [comment]
@sandervanteinde - Thank you for your contribution.

The API Environment.GetEnvironmentVariable("MYVAR") will look for the requested variable from the environment where the application is running. The steps you described above will launch the application inside the debugger with the environment of the system where the debugger/IDE is installed and running. Currently, the only supported way to set that value for the given environment is to set it at the system level. One way maybe to 'set MYVAR=value' from the VS2019 development command before launching devenv.

Alternatively, you can use the simulator to debug your module(s). The simulator uses docker containers for launching each module in the solution. To set environment variables in this scenario, you can add the following entry in the 'createOptions' of each module: "Env": [ "MYVAR=Hello MyVar", "MYVAR2=Hello MyVar2" ]
