### ISSUE TITLE
Is it possible to debug a DirectMethod using the simulator?

### ISSUE THREAD

**Issue by dvescovi1** [Azure/iotedgehubdev#383]
I am using the IoT Edge simulator with VS2022.
I am including the SimulatedTemperatureSensorModule as a source C# module (not pulled from mcr).
I setup the IoT Edge device connection string as one of my edge devices as defined in Azure IoT hub.

I can set break points in Program.cs for messages generated by the module and that works.
I can see the telemetry messages generated with Device Explorer.

I was trying to debug a DirectMethod call but these messages do not seem to be getting through.
Is it possible to interactively debug IoT DirectMethod or Message To Device as an IoT edge module?

**Comment by marianan** [comment]
hello @dvescovi1 , direct methods should be no different than telemetry messages in terms of debugging. Can you confirm that the direct method code is invoked?

**Comment by dvescovi1** [comment]
Can you show me how to invoke a direct method to an edge module using Azure IoT Explorer or the Device Explorer Twin tools?
Both these standalone tools can invoke a Direct Method to a "device" but I can not figure how to invoke a Direct Method to a "module on a device" i.e. IoT  Edge device. 

It is possible to do this using the IoT hub in Azure portal GUI but unfortunately it does not work with schema 1.2 only the old 1.1

**Comment by marianan** [comment]
@dvescovi1 thanks for mentioning the schemaVersion. Actually the portal does not yet support schemaVersion 1.2, the supported versions on the portal are 1.0 and 1.1 at the moment. I wonder if you can use az cli instead to validate your scenario. 
https://docs.microsoft.com/en-us/azure/iot-edge/module-edgeagent-edgehub?view=iotedge-2020-11#edgehub-desired-properties
https://docs.microsoft.com/en-us/azure/iot-edge/module-edgeagent-edgehub?view=iotedge-2020-11#edgeagent-desired-properties

**Comment by marianan** [comment]
Closing the issue due to inactivity. If the original symptoms persist, please file a new issue.
