### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by TechplexEngineer** [Azure/iotedgehubdev#394]
Minor typo on: https://github.com/Azure/iotedgehubdev/wiki/Azure-IoT-EdgeHub-Dev-Tool

`Seruity Daemon: It manages the credential of each IoT Edge Module and provide the credential to IoT Edge Module to open connection to edgeHub.`

Should read:
`Security Daemon: It manages the credential of each IoT Edge Module and provide the credential to IoT Edge Module to open connection to edgeHub.`

**Comment by konichi3** [comment]
Thanks @TechplexEngineer for the typo. Fixed the Wiki.
