### ISSUE TITLE
Announcing the Azure IoT Edge tool offerings in maintenance mode

### ISSUE THREAD

**Issue by konichi3** [Azure/iotedgehubdev#396]
As Azure IoT Edge product continues to evolve with [new features](https://github.com/Azure/iotedge/releases) and updated version to the LTS 1.4 (Long term service), one of our goals is to ensure we deliver consistent ways to develop, debug and test Azure IoT Edge modules on various version of Azure IoT Edge.

To best support the consistency across heterogenous developer environments and requirements, we have now published [a new documentation](https://aka.ms/newiotedgedev) which describes how to develop, debug and test Azure IoT Edge modules using command line interface.
This is a new recommended way to develop Azure IoT Edge modules.

With this new way, effective immediately, we are putting these product offering in maintenance mode where we are making minimum updates/changes to the products moving forward. Note that these products will continue to be available via either Marketplace or GitHub release pages.

These product are:
• [Azure IoT Edge extension to Visual Studio Code](https://github.com/microsoft/vscode-azure-iot-edge/)
• [Azure IoT Edge extension to Visual Studio 2019/2022](https://github.com/microsoft/vs-azure-iot-edge-docs/)
• [IoTEdgeHubDev tool](https://github.com/Azure/iotedgehubdev/)
• [Azure DevOps pipeline for IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment-classic?view=iotedge-2020-11)

thank you,
Azure IoT Edge team

**Comment by fswane** [comment]
Hi @konichi3 

For clarification, is the Azure IoT Dev Tool (https://pypi.org/project/iotedgedev/) also in maintenance mode (i.e. to be deprecated) or is this the appropriate tool to continue to develop edge solutions with?

Regards
Francois

**Comment by konichi3** [comment]
Hi @fswane 

Azure IoT Dev Tool is not in maintenance mode. We continue to invest on the tool and encourage to use to develop IoT Edge solutions.

thanks!
Koichi

**Comment by DMaxwell02** [comment]
The link above for the new documentation for how to develop and test an IoT Edge Module is for the Visual Studio Code method but ignores the problems in the Visual Studio 2022 method. 

Bottom line, the documentation and support for developing IoT Edge modules in Visual Studio 2022 are out dated and it even appears that Microsoft may be half hearted in IoT Edge module development as a whole. How do we find the roadmap?

**Comment by marianan** [comment]
@DMaxwell02 with the updated documentation, the only IDE specific parts are related to remote debugging. Here is a pointer to setting up remote debugging in Visual Studio - https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022 . Please let us know if you run into any issues while developing and debugging IoT Edge modules with Visual Studio.

**Comment by Hevgen** [comment]
The actual "new documentation" describes using of Azure IoT Edge Dev Tool as one of the possible variants to develop a custom module.  I see "You can choose either the Azure IoT Edge Dev Tool CLI or the Azure IoT Edge tools for VS Code extension as your IoT Edge development tool" by the link from the announcement. There is nothing like "This is a new recommended way to develop Azure IoT Edge modules." This is state on 01.01.2023. 
And the tutorial says: "Use the IoT Edge tools for Visual Studio Code" at https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4
So, is IoT Edge 1.4 (LST) documentation still not correct after 4 months since this announcement or are IoT Edge tools for VS recommended for development again?

**Comment by konichi3** [comment]
The new CLI way isn't a new feature that introduce a way to develop IoT Edge modules per se. It's meant to provide alternate way to scaffold IoT Edge solutions with sample modules, deployment manifest templates using CLI rather than the GUI via VSCode or VS extension. The work we have done were based on the customer's feedback.

VS/VSCode extensions continue to be available for module development but we recommend the CLI way with v1.4 LTS. 

On the documentation front, we plan to make updates to validate the links across documentations to promote the CLI way rather than VS/VSCode.

**Comment by Vic152** [comment]
With this. How does one create deployment manifest in az cli? Currently all the existing documentation point to VS Code to create manifest from the template.

**Comment by mikolajwalus** [comment]
With this changes local modules development became impossible and having remote device makes development super painful. In legacy approach i was able to run azureiotedge-hub image in docker, than configure my app using connection string, than just run my app locally and debug. Now I have to 1)build image (takes time), 2)deploy it to device, 3) connect to remote device via ssh if I want to debug. Than again if i want to change something in my code and see how it works i have to do points 1-3 again. Does Microsoft want to provide such poor developer experience or am I missing something here? If developing modules is so  painful than I will have to reconsider using IoT Edge solution

**Comment by codeminic** [comment]
> With this changes local modules development became impossible and having remote device makes development super painful. In legacy approach i was able to run azureiotedge-hub image in docker, than configure my app using connection string, than just run my app locally and debug. Now I have to 1)build image (takes time), 2)deploy it to device, 3) connect to remote device via ssh if I want to debug. Than again if i want to change something in my code and see how it works i have to do points 1-3 again. Does Microsoft want to provide such poor developer experience or am I missing something here? If developing modules is so painful than I will have to reconsider using IoT Edge solution at all

This. I feel your fustration. I tried the new tooling and havn't even been able to get it up and running. This is a major step back and i really hope they release something better, but if you have a look at the Github Repos, this does not seem to be the case. For now, i'm going with the old tooling.. as long as possible

**Comment by kitsunekyo** [comment]
the [new documentation](https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4&tabs=csharp&pivots=iotedge-dev-cli#set-up-tools) you've linked to still references the Azure IoT Edge Dev Tool as recommended approach for development.

is the tool now recommended or not? in the last days i've found countless contradicting information.

is the PR truly completed, or could it be the case that you've missed some documentation?

**Comment by Hevgen** [comment]
> is the PR truly completed, or could it be the case that you've missed some documentation? [this section](https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4&tabs=node&pivots=iotedge-dev-cli#create-a-container-registry) of the "new" documentation also references the Azure IoT Edge vscode extension.

No, the case is "we really don't care about documentation" and "you don't like CLI way? It is your problem".
There are other documentation problems which was referenced years ago and are ignored. MS propose to correct documentation yourself for some cases.
