### ISSUE TITLE
iotedgehubdev simulator getting Unauthorized error 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/iotedgehubdev#405]
Hi all ,
i am trying to run edge module in iotedgehubdev simulator running into Unauthorized  exception 
i configured iot edge device connection string :  iotedgehubdev setup -c "edge-device-connection-string"
it configured successfully ,but running  into  Unauthorized exception 

can someone help me here 
 

exception :
ERROR: (401, '{"Message":"{\\"errorCode\\":401002,\\"trackingId\\":\\"b8162c1e15e74da88a37603ed75d2622-G:0-TimeStamp:11/14/2022 13:46:15\\",\\"message\\":\\"Unauthorized\\",\\"timestampUtc\\":\\"2022-11-14T13:46:15.7466888Z\\"}","ExceptionMessage":""}')

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/33150961/201676186-d87a4997-c159-4825-b72f-bf291f303a88.png">

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/33150961/201753997-4ef93f26-7419-41eb-8ecf-b180dfc5139b.png">

**Comment by konichi3** [comment]
@lakshmisivareddy Can you verify whether the same symptom occurs with VM or a physical device?
