### ISSUE TITLE
iotedgehubdev installation path is not added to PATH

### ISSUE THREAD

**Issue by ghost** [Azure/iotedgehubdev#42]
I saw warnings said the installation path is not added to PATH.
Since all the iotedgehubdev operations in the test plan are executed through command line, we might need to consider add application location to PATH by default.

**Comment by rido-min** [comment]
I still hit this issue. I was expecting having these instructions on the README

**Comment by adashen** [comment]
@rido-min, Thanks for the suggestion, we will add it as notes in the README.
