### ISSUE TITLE
Installation failure with Python 3.7

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#5]
OS : Windows10
Python version:3.7.0
Docker version:17.12.0-rc-win47 * Windows Container

run "pip install -e ." failed on Python 3.7.0
![image](https://user-images.githubusercontent.com/35018765/42198410-701eb23c-7eba-11e8-9fbd-3edc6d94ace7.png)

![image](https://user-images.githubusercontent.com/35018765/42198416-786c9288-7eba-11e8-8115-0a4731cbf228.png)

**Comment by LazarusX** [comment]
Just verified that installation succeeded with Python 3.7.
