### ISSUE TITLE
do we need to delete the edgehub.json when uninstall iotedgehubdev

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#70]
OS: windows10

steps:
1. pip install iotedgehubdev

2. Iotedgehubdev setup –c "HostName=v-czghub0706.azure-devices.net;DeviceId=windowstest;SharedAccessKey=jcYNgGqzJ5mG1+NqBQIysO3y0Egjde2OueayM4UxQig="

10 days later,  this v-czghub0706 iot hub is expired , then I  uninstall iotedgehubdev and upgrade again

3. pip uninstall iotedgehubdev

4.pip install --upgrade iotedgehubdev

5.open c# module solution , build and run iot edge solution in simulator

ERROR: Error: HTTPSConnectionPool(host='v-czghub0706.azure-devices.net', port=443): Max retries exceeded with url: /devices/windowstest/modules/$edgeHub?api-version=2017-11-08-preview (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003A674E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

![image](https://user-images.githubusercontent.com/35018765/43820376-abd14234-9b18-11e8-9e7d-05a99d934993.png)

**Comment by SLdragon** [comment]
pip uninstall only remove package, and cannot remove other files, so close this issue
