### ISSUE TITLE
 The specified SAS token has an invalid signature on Pi/Ubuntu/windows10

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#79]
1.  sudo iotedgehubdev setup -c "HostName=abc1234.azure-devices.net;DeviceId=pidevice;SharedAccessKey=OVPoprAvcD92NV0ogtNQMv44Kw/zyY18D14yoL8VGb4="

2. iotedgehubdev start -d deployment0910.json

3. docker logs -f edgeHubDev

![image](https://user-images.githubusercontent.com/35018765/45272312-181c1380-b4df-11e8-8a43-f6b109699452.png)

**Comment by adashen** [comment]
@czgtest is it still reproducible on the new version after fixing the auth error?
